import { TemplateCreationAttributes } from '../models/Template'

export const SEED_TEMPLATES: TemplateCreationAttributes[] = [
  // ======== API 模板 ========
  {
    name: 'Slack 发送消息',
    description: '通过 Incoming Webhook 向 Slack 频道发送消息',
    type: 'api',
    category: '即时通讯',
    icon: '💬',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      url: 'https://hooks.slack.com/services/{{webhookPath}}',
      method: 'POST',
      headers: '{"Content-Type": "application/json"}',
      body: '{"text": "{{$input}}"}',
    }),
  },
  {
    name: '飞书机器人通知',
    description: '通过飞书自定义机器人 webhook 发送群消息',
    type: 'api',
    category: '即时通讯',
    icon: '📘',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      url: 'https://open.feishu.cn/open-apis/bot/v2/hook/{{webhookPath}}',
      method: 'POST',
      headers: '{"Content-Type": "application/json"}',
      body: '{"msg_type": "text","content": {"text": "{{$input}}"}}',
    }),
  },
  {
    name: 'GitHub 创建 Issue',
    description: '在指定仓库创建一个 GitHub Issue',
    type: 'api',
    category: '版本控制',
    icon: '🐙',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      url: 'https://api.github.com/repos/{{owner}}/{{repo}}/issues',
      method: 'POST',
      headers: '{"Authorization": "Bearer {{$env.GITHUB_TOKEN}}","Content-Type": "application/json"}',
      body: '{"title": "{{$input}}","body": "{{description}}"}',
    }),
  },
  {
    name: 'Telegram 发送消息',
    description: '通过 Telegram Bot API 发送消息',
    type: 'api',
    category: '即时通讯',
    icon: '✈️',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      url: 'https://api.telegram.org/bot{{$env.TELEGRAM_BOT_TOKEN}}/sendMessage',
      method: 'POST',
      headers: '{"Content-Type": "application/json"}',
      body: '{"chat_id": "{{chatId}}","text": "{{$input}}"}',
    }),
  },
  {
    name: '企业微信机器人',
    description: '通过企业微信机器人 webhook 发送群消息',
    type: 'api',
    category: '即时通讯',
    icon: '💼',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key={{webhookKey}}',
      method: 'POST',
      headers: '{"Content-Type": "application/json"}',
      body: '{"msgtype": "text","text": {"content": "{{$input}}"}}',
    }),
  },
  {
    name: 'DingTalk 机器人',
    description: '通过钉钉机器人 webhook 发送群消息',
    type: 'api',
    category: '即时通讯',
    icon: '🔔',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      url: 'https://oapi.dingtalk.com/robot/send?access_token={{accessToken}}',
      method: 'POST',
      headers: '{"Content-Type": "application/json"}',
      body: '{"msgtype": "text","text": {"content": "{{$input}}"}}',
    }),
  },

  // ======== MCP 配置 ========
  {
    name: 'Playwright (浏览器自动化)',
    description: '通过 Playwright 控制浏览器进行网页操作和截图',
    type: 'mcp',
    category: '浏览器',
    icon: '🎭',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      transportType: 'stdio',
      command: 'npx',
      args: JSON.stringify(['@anthropic-ai/mcp-playwright']),
    }),
  },
  {
    name: 'Filesystem (文件系统)',
    description: '安全的文件系统操作，支持读写、搜索、目录管理',
    type: 'mcp',
    category: '开发工具',
    icon: '📁',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      transportType: 'stdio',
      command: 'npx',
      args: JSON.stringify(['-y', '@anthropic-ai/mcp-filesystem', '{{allowedDir}}']),
    }),
  },
  {
    name: 'GitHub MCP',
    description: 'GitHub 仓库管理：PR、Issue、代码搜索等',
    type: 'mcp',
    category: '版本控制',
    icon: '🐙',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      transportType: 'stdio',
      command: 'npx',
      args: JSON.stringify(['-y', '@anthropic-ai/mcp-github']),
    }),
  },
  {
    name: 'Sqlite 数据库',
    description: 'SQLite 数据库查询和管理',
    type: 'mcp',
    category: '数据库',
    icon: '🗄️',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      transportType: 'stdio',
      command: 'npx',
      args: JSON.stringify(['-y', '@anthropic-ai/mcp-sqlite', '{{dbPath}}']),
    }),
  },

  // ======== 代码片段 ========
  {
    name: 'JSON 转 CSV',
    description: '将 JSON 数组转换为 CSV 格式',
    type: 'code',
    category: '数据处理',
    icon: '📊',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      code: 'const data = JSON.parse($input)\nif (!Array.isArray(data)) return "需要 JSON 数组输入"\nconst headers = Object.keys(data[0])\nconst rows = data.map(item => headers.map(h => JSON.stringify(item[h] ?? "")).join(","))\nreturn [headers.join(","), ...rows].join("\\n")',
      language: 'javascript',
    }),
  },
  {
    name: '数组聚合统计',
    description: '对数值数组计算总和、平均值、最大值、最小值',
    type: 'code',
    category: '数据处理',
    icon: '📈',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      code: 'const arr = JSON.parse($input)\nif (!Array.isArray(arr)) return "需要数组输入"\nconst nums = arr.map(Number).filter(n => !isNaN(n))\nreturn JSON.stringify({\n  count: nums.length,\n  sum: nums.reduce((a, b) => a + b, 0),\n  avg: (nums.reduce((a, b) => a + b, 0) / nums.length).toFixed(2),\n  min: Math.min(...nums),\n  max: Math.max(...nums),\n}, null, 2)',
      language: 'javascript',
    }),
  },
  {
    name: '文本分块',
    description: '将长文本按指定大小分块，支持重叠',
    type: 'code',
    category: '文本处理',
    icon: '✂️',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      code: 'const size = 500\nconst overlap = 50\nconst text = $input\nconst chunks = []\nlet i = 0\nwhile (i < text.length) {\n  chunks.push(text.slice(i, i + size))\n  i += size - overlap\n}\nreturn JSON.stringify(chunks, null, 2)',
      language: 'javascript',
    }),
  },
  {
    name: '数据去重',
    description: '按指定字段对 JSON 数组去重',
    type: 'code',
    category: '数据处理',
    icon: '🔄',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      code: 'const data = JSON.parse($input)\nif (!Array.isArray(data)) return "需要数组输入"\nconst field = params?.field || "id"\nconst seen = new Set()\nreturn JSON.stringify(data.filter(item => {\n  const val = item[field]\n  if (seen.has(val)) return false\n  seen.add(val)\n  return true\n}), null, 2)',
      language: 'javascript',
    }),
  },
  {
    name: '日期格式化',
    description: '将各种格式的日期字符串统一格式化',
    type: 'code',
    category: '文本处理',
    icon: '📅',
    author: 'system',
    version: '1.0.0',
    content: JSON.stringify({
      code: 'const format = params?.format || "YYYY-MM-DD"\nconst date = new Date($input)\nif (isNaN(date.getTime())) return "无效日期"\nconst map = {\n  "YYYY": date.getFullYear(),\n  "MM": String(date.getMonth() + 1).padStart(2, "0"),\n  "DD": String(date.getDate()).padStart(2, "0"),\n  "HH": String(date.getHours()).padStart(2, "0"),\n  "mm": String(date.getMinutes()).padStart(2, "0"),\n  "ss": String(date.getSeconds()).padStart(2, "0"),\n}\nreturn Object.entries(map).reduce((s, [k, v]) => s.replace(k, v), format)',
      language: 'javascript',
    }),
  },
]
